/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notifications/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 透過 LINE Messaging API 推播訊息給住戶（包裹到貨 / 訪客到達通知） */
        post: operations["sendLineMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得包裹列表 */
        get: operations["listPackages"];
        put?: never;
        /** 登記新到貨包裹（登記後狀態為 pending，需再呼叫 /packages/{id}/notify 通知住戶） */
        post: operations["registerPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package}/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 通知住戶包裹已送達（狀態 pending → notified，並透過 LINE Messaging API 推播） */
        patch: operations["notifyPackage"];
        trace?: never;
    };
    "/packages/{package}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 標記包裹已被領取 */
        patch: operations["collectPackage"];
        trace?: never;
    };
    "/parking/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得車輛進出紀錄 */
        get: operations["listParkingLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parking/recognize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 送入車牌號碼進行辨識並登記進出紀錄 */
        post: operations["recognizeParking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得訪客 / 外送登記列表 */
        get: operations["listVisitors"];
        put?: never;
        /** 登記訪客或外送到達 */
        post: operations["registerVisitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visitors/{visitor}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新訪客狀態（等待中 → 已通知 → 已進入 → 已離開） */
        patch: operations["updateVisitorStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PackageItem: {
            id: number;
            trackingNo: string;
            recipientUnit: string;
            recipientName: string;
            courier: string | null;
            /** @enum {string} */
            status: "pending" | "notified" | "collected";
            /** Format: date-time */
            arrivedAt: string;
            /** Format: date-time */
            collectedAt: string | null;
        };
        ParkingLog: {
            id: number;
            plateNumber: string;
            /** @enum {string} */
            direction: "in" | "out";
            /** @enum {string} */
            status: "success" | "failed";
            ownerName: string | null;
            /** Format: date-time */
            recognizedAt: string;
        };
        VisitorLog: {
            id: number;
            visitorName: string;
            /** @enum {string} */
            visitorType: "guest" | "delivery";
            targetUnit: string;
            /** @enum {string} */
            status: "waiting" | "notified" | "entered" | "left";
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            notifiedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendLineMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example A-1203 */
                    targetUnit: string;
                    /** @example 您有一件包裹已送達管理室，請盡快領取。 */
                    message: string;
                };
            };
        };
        responses: {
            /** @description 已送出 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    listPackages: {
        parameters: {
            query?: {
                status?: "pending" | "notified" | "collected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"][];
                };
            };
        };
    };
    registerPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    trackingNo: string;
                    /** @example A-1203 */
                    recipientUnit: string;
                    recipientName: string;
                    courier?: string | null;
                };
            };
        };
        responses: {
            /** @description 登記成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
        };
    };
    notifyPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
            /** @description 包裹不是待通知狀態 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    collectPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
            /** @description 包裹尚未通知住戶 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listParkingLogs: {
        parameters: {
            query?: {
                direction?: "in" | "out";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLog"][];
                };
            };
        };
    };
    recognizeParking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example ABC-1234 */
                    plateNumber: string;
                    /** @enum {string} */
                    direction: "in" | "out";
                };
            };
        };
        responses: {
            /** @description 辨識完成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLog"];
                };
            };
        };
    };
    listVisitors: {
        parameters: {
            query?: {
                status?: "waiting" | "notified" | "entered" | "left";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"][];
                };
            };
        };
    };
    registerVisitor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    visitorName: string;
                    /** @enum {string} */
                    visitorType: "guest" | "delivery";
                    /** @example A-1203 */
                    targetUnit: string;
                };
            };
        };
        responses: {
            /** @description 登記成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"];
                };
            };
        };
    };
    updateVisitorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitor: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "waiting" | "notified" | "entered" | "left";
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"];
                };
            };
        };
    };
}
