/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登入並取得 Bearer token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（撤銷目前這組 token） */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得目前登入的使用者資訊（驗證 token 是否有效用） */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接收 LINE 官方帳號的 webhook 事件（由 LINE 平臺呼叫，不是前端呼叫）
         * @description 需在 LINE Developers Console 的 Messaging API 設定頁把 Webhook URL 指到這支端點，並開啟「Use webhook」。請求會帶 X-Line-Signature header，本端點會用 Channel secret 驗證來源真偽後才處理事件。
         */
        post: operations["receiveLineWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 透過 LINE Messaging API 推播訊息給住戶（包裹到貨 / 訪客到達通知） */
        post: operations["sendLineMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得包裹列表 */
        get: operations["listPackages"];
        put?: never;
        /** 登記新到貨包裹（登記後狀態為 pending，需再呼叫 /packages/{id}/notify 通知住戶） */
        post: operations["registerPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package}/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 通知住戶包裹已送達（狀態 pending → notified，並透過 LINE Messaging API 推播） */
        patch: operations["notifyPackage"];
        trace?: never;
    };
    "/packages/{package}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 標記包裹已被領取 */
        patch: operations["collectPackage"];
        trace?: never;
    };
    "/parking/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得車輛進出紀錄 */
        get: operations["listParkingLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parking/recognize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 送入車牌號碼進行辨識並登記進出紀錄 */
        post: operations["recognizeParking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parking/nearby-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢附近公共停車場即時空位（轉發交通部 TDX 開放資料，OAuth2 client_credentials） */
        get: operations["listNearbyParkingAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得訪客 / 外送登記列表 */
        get: operations["listVisitors"];
        put?: never;
        /** 登記訪客或外送到達 */
        post: operations["registerVisitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visitors/{visitor}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新訪客狀態（等待中 → 已通知 → 已進入 → 已離開） */
        patch: operations["updateVisitorStatus"];
        trace?: never;
    };
    "/weather/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得指定縣市的 36 小時天氣預報（轉發中央氣象署 CWA 開放資料） */
        get: operations["getWeatherForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得指定縣市目前生效中的天氣特報（轉發中央氣象署 CWA 開放資料） */
        get: operations["listWeatherAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PackageItem: {
            id: number;
            trackingNo: string;
            recipientUnit: string;
            recipientName: string;
            courier: string | null;
            /** @enum {string} */
            status: "pending" | "notified" | "collected";
            /** Format: date-time */
            arrivedAt: string;
            /** Format: date-time */
            collectedAt: string | null;
        };
        ParkingLog: {
            id: number;
            plateNumber: string;
            /** @enum {string} */
            direction: "in" | "out";
            /** @enum {string} */
            status: "success" | "failed";
            ownerName: string | null;
            /** Format: date-time */
            recognizedAt: string;
        };
        ParkingLotAvailability: {
            /** @example TPE_C001 */
            id: string;
            /** @example 市民廣場地下停車場 */
            name: string;
            address: string | null;
            /** @description 目前剩餘車位；null 表示現場未回報（TDX 原始值為 -1） */
            availableSpaces: number | null;
            totalSpaces: number | null;
            /** @example 營業中 */
            serviceStatus: string;
            /** @example 尚有空位 */
            fullStatus: string;
            /** Format: date-time */
            updatedAt: string | null;
        };
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
        };
        VisitorLog: {
            id: number;
            visitorName: string;
            /** @enum {string} */
            visitorType: "guest" | "delivery";
            targetUnit: string;
            /** @enum {string} */
            status: "waiting" | "notified" | "entered" | "left";
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            notifiedAt: string | null;
        };
        WeatherAlert: {
            /** @example 大雨 */
            phenomena: string;
            /** @example 特報 */
            significance: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
        };
        WeatherForecast: {
            /** @example 臺北市 */
            city: string;
            /** @example 多雲 */
            description: string;
            /** @example 24 */
            minTemp: number;
            /** @example 31 */
            maxTemp: number;
            /**
             * @description 降雨機率 (%)
             * @example 20
             */
            pop: number;
            /** @example 悶熱 */
            comfort: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example demo@buildingos.test
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example buildingos-demo
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 登入成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                        user?: components["schemas"]["User"];
                    };
                };
            };
            /** @description 帳號或密碼錯誤 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已登出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未登入或 token 已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description 未登入或 token 已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiveLineWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256(Channel secret, raw body) 的 base64 結果 */
                "X-Line-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已處理（含簽章驗證通過但沒有事件的健康檢查請求） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 簽章驗證失敗 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 後端尚未設定 LINE_CHANNEL_SECRET */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendLineMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example A-1203 */
                    targetUnit: string;
                    /** @example 您有一件包裹已送達管理室，請盡快領取。 */
                    message: string;
                };
            };
        };
        responses: {
            /** @description 已送出 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    listPackages: {
        parameters: {
            query?: {
                status?: "pending" | "notified" | "collected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"][];
                };
            };
        };
    };
    registerPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    trackingNo: string;
                    /** @example A-1203 */
                    recipientUnit: string;
                    recipientName: string;
                    courier?: string | null;
                };
            };
        };
        responses: {
            /** @description 登記成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
        };
    };
    notifyPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
            /** @description 包裹不是待通知狀態 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    collectPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageItem"];
                };
            };
            /** @description 包裹尚未通知住戶 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listParkingLogs: {
        parameters: {
            query?: {
                direction?: "in" | "out";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLog"][];
                };
            };
        };
    };
    recognizeParking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example ABC-1234 */
                    plateNumber: string;
                    /** @enum {string} */
                    direction: "in" | "out";
                };
            };
        };
        responses: {
            /** @description 辨識完成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLog"];
                };
            };
        };
    };
    listNearbyParkingAvailability: {
        parameters: {
            query?: {
                /** @description 縣市（英文代碼，例如 Taipei），預設值可於後端設定 */
                city?: string;
                /** @description 回傳筆數上限（此 API 沒有座標可篩選「附近」，單一縣市可能有上千筆資料） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLotAvailability"][];
                };
            };
            /** @description 不支援的縣市代碼 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 後端尚未設定 TDX_CLIENT_ID / TDX_CLIENT_SECRET */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVisitors: {
        parameters: {
            query?: {
                status?: "waiting" | "notified" | "entered" | "left";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"][];
                };
            };
        };
    };
    registerVisitor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    visitorName: string;
                    /** @enum {string} */
                    visitorType: "guest" | "delivery";
                    /** @example A-1203 */
                    targetUnit: string;
                };
            };
        };
        responses: {
            /** @description 登記成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"];
                };
            };
        };
    };
    updateVisitorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitor: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "waiting" | "notified" | "entered" | "left";
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorLog"];
                };
            };
        };
    };
    getWeatherForecast: {
        parameters: {
            query?: {
                /** @description 縣市名稱，例如「臺北市」，預設值可於後端設定 */
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherForecast"];
                };
            };
            /** @description 查無此縣市的預報資料 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 後端尚未設定 CWA_API_KEY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWeatherAlerts: {
        parameters: {
            query?: {
                /** @description 縣市名稱，例如「臺北市」，預設值可於後端設定 */
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功（沒有特報時回傳空陣列） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherAlert"][];
                };
            };
            /** @description 後端尚未設定 CWA_API_KEY */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
